# Generated by Django 2.2.6 on 2019-10-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('battingstyle', models.CharField(max_length=150)),
                ('bowlingstyle', models.CharField(max_length=150)),
                ('iccrank', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teamranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('team', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=150)),
                ('teamicon', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
