# Generated by Django 2.2.6 on 2019-10-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='head',
            field=models.CharField(max_length=500),
        ),
    ]
