# Generated by Django 2.2.6 on 2019-11-03 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRankingTestBat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRankingOdiBat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('player', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Teams')),
            ],
        ),
    ]
