# Generated by Django 2.2.6 on 2019-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_playerrankingodibat_playerrankingtestbat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
